[[pages]]
path = "seg_train.py"
name = "Train NMF Virtual Staining"

[[pages]]
path = "umap_train.py"
name = "Train UMAP Virtual Staining"

[[pages]]
path = "deploy.py"
name = "Run Virtual Stain (NMF or Kmeans)"