[[pages]]
path = "show_ion_images.py"
name = "Show ION images"

[[pages]]
path = "explore.py"
name = "Dataset Exploration"

[[pages]]
path = "saliency_optimization.py"
name = "Saliency Optimization"

[[pages]]
path = "seg_train.py"
name = "Train NMF or Kmeans"

[[pages]]
path = "dimensionality_reduction_train.py"
name = "Train Dimensionality Reduction Color Visualization model"

[[pages]]
path = "deploy.py"
name = "Run Virtual Stain"