[[pages]]
path = "nmf_train.py"
name = "Train NMF Virtual Staining"

[[pages]]
path = "deploy.py"
name = "Run NMF-Stain"

[[pages]]
path = "umap_train.py"
name = "Train UMAP Virtual Staining"