[[pages]]
path = "seg_train.py"
name = "Train NMF or Kmeans"

[[pages]]
path = "dimensionality_reduction_train.py"
name = "Train Dimensionality Reduction Color Visualization model"

[[pages]]
path = "deploy.py"
name = "Run Virtual Stain"